version: '3'

services:
  in322:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8080:80"
    volumes:
      - .:/bin223
    command: bash