version: '3'

services:
  in322:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - .:/rhel_rootless
    ports:
      - "2224:22"
    command: bash