services:
  openvpn:
    image: openvpn/openvpn:3.4
    container_name: openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - ./ovpn-data:/etc/openvpn
    restart: unless-stopped
