version: '3'

services:
  in322:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - "8080:80"
    volumes:
      # Mount the current directory to /ansible-initiation in the container
      - .:/ansible-initiation
    command: bash